### PR TITLE
fix: rearrange server files

### LINKED ISSUE #25: updata file structure
the task :
 - create a server folder in car-trade folder
 - Put the src file inside the server file 
 -  put all folders that have relation with a server inside the src folder else test folder stay in server folder and json fils and config fils 
 -  ranking database fils and folder 
 - fix the eslint error that shows because change the folders

### PR DESCRIPTION
**Pull request by husamkamal**
create a server folder in car-trade folder and Put the src file inside the server file and put all folders that have relation with a server inside the src folder else test folder stay in server folder and json fils and config fils and ranking database fils and folder and fix the eslint error that shows because change the folders

### CODE REVIEW

File: server/src/db/models/image.ts [hunk 1]
```diff
@@ -1,5 +1,5 @@
 import { DataTypes } from 'sequelize';
-import sequelize from '../config/connection';
+import sequelize from '../db/config/connection';
```
Comment (LinaYahya) [inline server/src/db/models/image.ts]:
```suggestion
import sequelize from '../config/connection';
```

File: server/src/db/models/customer.ts [hunk 2]
```diff
@@ -1,5 +1,5 @@
 import { DataTypes } from 'sequelize';
-import sequelize from '../config/connection';
+import sequelize from '../db/config/connection';
```
Comment (LinaYahya) [inline server/src/db/models/customer.ts]:
```suggestion
import sequelize from '../config/connection';
```

File: server/src/db/models/car.ts [hunk 3]
```diff
@@ -1,5 +1,5 @@
 import { DataTypes } from 'sequelize';
-import sequelize from '../config/connection';
+import sequelize from '../db/config/connection';
```
Comment (LinaYahya) [inline server/src/db/models/car.ts]:
```suggestion
import sequelize from '../config/connection';
```

**Review by LinaYahya — CHANGES_REQUESTED** [review]

**Review by LinaYahya — APPROVED** [review]

**Review by mai-mohammed — APPROVED** [review]

**Review by abdou059 — APPROVED** [review]
