### PR TITLE
fix: function in filter

### LINKED ISSUE #167: make custome hooke to filter

### PR DESCRIPTION
**Pull request by husamkamal**
delete all function in the filter components and create custom hook and add all function in it

### CODE REVIEW

**Review by abdou059 — APPROVED** [review]

File: client/src/Hooks/UseFIlter.tsx [hunk 1]
```diff
@@ -0,0 +1,129 @@
+import { SetStateAction, useEffect, useState } from 'react';
+import { useLocation } from 'react-router-dom';
+import { CarsFilterProps, CarsWithImagesData, Params } from '../interfaces';
+import httpInstance from '../services';
+
+export default function useFIlter({
```
Comment (mai-mohammed) [inline client/src/Hooks/UseFIlter.tsx:6]: edit hook name

**Review by mai-mohammed — APPROVED** [review]

**Review by mai-mohammed — APPROVED** [review]

**Review by tariqabusada — APPROVED** [review]
